// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serialize/protodata/test.proto

/*
Package protodata is a generated protocol buffer package.

It is generated from these files:
	serialize/protodata/test.proto
	serialize/protodata/test1.proto

It has these top-level messages:
	Test
	Test1
	Test2
*/
package protodata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Str              *string `protobuf:"bytes,2,req,name=str" json:"str,omitempty"`
	Opt              *int32  `protobuf:"varint,3,opt,name=opt" json:"opt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Test) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *Test) GetOpt() int32 {
	if m != nil && m.Opt != nil {
		return *m.Opt
	}
	return 0
}

func init() {
	proto.RegisterType((*Test)(nil), "protodata.Test")
}

func init() { proto.RegisterFile("serialize/protodata/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x4e, 0x2d, 0xca,
	0x4c, 0xcc, 0xc9, 0xac, 0x4a, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x49, 0x2c, 0x49, 0xd4,
	0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x73, 0x85, 0x38, 0xe1, 0xa2, 0x4a, 0x56, 0x5c, 0x2c, 0x21,
	0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xac, 0x41,
	0x4c, 0x99, 0x29, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0x25, 0x45, 0x12, 0x4c, 0x0a, 0x4c, 0x1a, 0x9c,
	0x41, 0x20, 0x26, 0x48, 0x24, 0xbf, 0xa0, 0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc4,
	0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x09, 0xbf, 0xce, 0x29, 0x67, 0x00, 0x00, 0x00,
}
